# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d3ec138d432969a50057f4f399f5b1dc116f7364342943ae3bf83de0361c8263f26987be98caa4c9ba6c3c1983974b03fa5f673d3c8e9a5799a49af05aa0121

test:
  secret_key_base: 25b618d522a75756cc46cc92698f9277421634d2508ed77a790533b0a212906d1f7cba0a27e8305dc20fd64fff87ee80c9a5d22e9c29471d0bace8aca68bc464

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
